web:
    build: .
    command: sh -c 'npm install; npm start'
    ports:
        - '3000:3000'
    volumes: 
        - /home/melonespc/bdnsql/tp2/star-wars-recetas/backend:/backend
    links:
        - "db:redis"
db:
    image: redis
    ports: 
        - "6379:6379"